"""empty message

Revision ID: bb7d77b2a4a1
Revises: fd4174154880
Create Date: 2025-06-15 00:11:35.877424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb7d77b2a4a1'
down_revision: Union[str, None] = 'fd4174154880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    # ### end Alembic commands ###
